# Generated by Django 2.2.2 on 2019-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productName', models.CharField(max_length=2000)),
                ('productSKU', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('productDesc', models.TextField()),
                ('productActive', models.BooleanField()),
            ],
        ),
    ]
